name: deploy-infra

on:
  push:
    paths:
      - "infra/**"
  workflow_dispatch:

env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9b2cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: felixgg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./infra/key-vault.bicep

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./infra/main.bicep

  deploy:
    #    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"

    steps:
      - uses: actions/checkout@main

      # login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Key Vault
      - name: deploy-key-vault
        run: |
          az deployment group create \
            --name "${{ env.USER_ALIAS }}-kv" \
            --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
            --template-file ./infra/key-vault.bicep \
            --parameters @./infra/parameters/key-vault.json \
            --subscription ${{ env.SUBSCRIPTION_ID_DEV }} \
            --verbose

      # Deploy Main Bicep File
      - name: deploy-main
        run: |
          az deployment group create \
            --name "${{ env.USER_ALIAS }}" \
            --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
            --template-file ./infra/main.bicep \
            --parameters @./infra/parameters/main.json \
            --subscription ${{ env.SUBSCRIPTION_ID_DEV }} \
            --verbose
